### ISSUE TITLE
Opening Mystery Data Crashes the game

### ISSUE THREAD

**Issue by BloodredAi** [SHNecro/ShanghaiEXE#1]
New to Shanghai, so not sure if this is a known bug or a new one. Seems to be consistent across all Mystery Data, i've tried opening the ones in the Class 2-1 Blackboard comp, the Fire Hydrant comp, and the Flowerbed comp. Haven't grinded enough money to buy the Unlocker equivalent to grab the locked mysterydata yet, so don't know if that also crashes.

Edit: Have been through the entire game up to the non-functional final boss. The only exception i've noted is the Ice Crystal sidequest, because that seems to be a cutscene rather than an actual Mystery Data. 

I've also been talking to a few friends and they do NOT have this issue, though i don't know if they're on the same version or not. I have all the things in the ReadMe installed, so i honestly have no clue what's causing it.

**Comment by SHNecro** [comment]
Fixed and replaced last release with e14_1.
Caused by separating rendering from game ticks in order for Turbo to work without redrawing the screen for every sped-up frame.
Likely there are more problems with the same cause, but the previous behavior was straight-up incorrect and would cause problems for any future changes.
