### ISSUE TITLE
A trio of cutscene failures.

### ISSUE THREAD

**Issue by BloodredAi** [SHNecro/ShanghaiEXE#2]
"Rocket Launcher" Cutscene in Border Concern Scenario locks the camera at an odd angle when it returns to Shanghai's perspective. Saving and quitting fixed it.

"President's Office" Cutscene in Border Concern Scenario. Nothing but the text boxes and a green background.

There's a few moments of green background when flying to the ROM base in Wriggle's stealth jet. It fixed itself though, so i'm guessing there was supposed to be an animation playing?

**Comment by SHNecro** [comment]
Found and fixed possibly related issue during undernet portal cutscene while playing up from my closest debug save.
Camera offsets were being set during Render rather than Update, so using turbo could cause a cutscene positioning teleport to happen between frames and and not update the camera before a relative camera move event fired.
The relative move would then pan from the last-used position, and be misaligned or completely off.

Currently getting to each of the mentioned cutscenes, my debug saves were very sparse.

**Comment by SHNecro** [comment]
First cutscene fixed, was a separate issue where events were marked as ended in the render loop, causing relative camera moves to repeat and throw itself offscreen.

**Comment by SHNecro** [comment]
Think those 3 issues had a common cause, they're all to do with scene transitions and I haven't seen them since I pushed the fix for the 1st one into source.

It'll be included in the new release in the next couple of days, feel free to recreate this issue if it's still occurring in that one.
