### ISSUE TITLE
Doubles my input in the custom screen occasionally

### ISSUE THREAD

**Issue by RiJect** [SHNecro/ShanghaiEXE#4]
Heyo, it's pretty much exactly what the title says. Occasionally (it doesn't seem to have any pattern) any input on the custom screen doubles. So if I press left, it jumps two spaces instead of one. This happens with both keyboard and controller.

**Comment by SHNecro** [comment]
Haven't been able to replicate this, but controllers/input is something I'm looking at next.
Does it happen for just one input, or does something get stuck and every input from then on gets doubled?

**Comment by RiJect** [comment]
It's completely random it seems. I can go 10 inputs without doubeling sometimes. And sometimes it seems to happen every input for a couple of inputs. There's no pattern at all.

**Comment by SHNecro** [comment]
Definitely seeing it now, temporary fix might be to switch to opengl mode.
I'll figure it out, probably has something to do with how directx mode sleeps to the monitor refresh, messing with the input polling.

**Comment by RiJect** [comment]
Unfortunately the problem persists in both DirectX and OpenGL if that helps any. I appreciate the help though!

**Comment by pa-me** [comment]
hi.
If fps is set to 60, try it.

**Comment by SHNecro** [comment]
Pretty sure I've got it, the custom screen uses key "press" for navigation, which was supposed to only fire once when the key is initially pressed.
I broke this when adding in queued updates to maintain framerate, since keys are updated every main loop but multiple updates might fire in one cycle if the desired update rate doesn't match the main loop. Those queued updates would then reuse the same key data, which includes a keypress that should have only fired once.

I've pushed the fix into the source, but I'm planning make a new release in the next few days, check it out then and feel free to recreate this issue if it persists.
