### ISSUE TITLE
Zenny Mystery Data message displaying twice in a row

### ISSUE THREAD

**Issue by BigCti** [SHNecro/ShanghaiEXE#8]
Another pretty self-explanatory title. Whenever I open GMD with Zenny in it, the message displays twice. It doesn't do this for anything else I get out of a Mystery Data, and it doesn't increase my Zenny amount twice; it's purely visual.

![ezgif-2-b479f560b8d5](https://user-images.githubusercontent.com/57572511/68535838-5ba22580-030e-11ea-89c0-c1c8d13fc211.gif)

**Comment by SHNecro** [comment]
Updated release to _1, should be fixed.

Broke when fixing the missing "Maximum HP increased by 20" etc. messages, forgot that Zenny and BugFrags used the same code and added the last-used dialogue instead of that extra message.

Wish the code were set up for unit testing, but I suppose we're lucky to have what we have at all.
